function formatJSON() { const i=document.getElementById('json-input').value; try { document.getElementById('json-output').value=JSON.stringify(JSON.parse(i),null,2); showStatus('json-status','Valid JSON','success'); } catch(e) { showStatus('json-status','Error: '+e.message,'error'); } }
function minifyJSON() { const i=document.getElementById('json-input').value; try { document.getElementById('json-output').value=JSON.stringify(JSON.parse(i)); showStatus('json-status','Minified','success'); } catch(e) { showStatus('json-status','Error: '+e.message,'error'); } }
function validateJSON() { const i=document.getElementById('json-input').value; try { JSON.parse(i); showStatus('json-status','Valid JSON','success'); document.getElementById('json-output').value=i; } catch(e) { showStatus('json-status','Error: '+e.message,'error'); } }
function jsonToYaml() { const i=document.getElementById('json-input').value; try { const o=JSON.parse(i); let y=''; for(let k in o) y+=k+': '+(typeof o[k]=='object'?JSON.stringify(o[k]):o[k])+'\n'; document.getElementById('json-output').value=y; showStatus('json-status','Converted','success'); } catch(e) { showStatus('json-status','Error','error'); } }
function clearJSON() { document.getElementById('json-input').value=''; document.getElementById('json-output').value=''; document.getElementById('json-status').textContent=''; }
function encodeBase64() { document.getElementById('base64-output').value=btoa(document.getElementById('base64-input').value); }
function decodeBase64() { try { document.getElementById('base64-output').value=atob(document.getElementById('base64-input').value); } catch(e) { document.getElementById('base64-output').value='Error'; } }
function clearBase64() { document.getElementById('base64-input').value=''; document.getElementById('base64-output').value=''; }
function timestampToDate() { const t=document.getElementById('timestamp-input').value; if(t) document.getElementById('timestamp-output').innerHTML=new Date(parseInt(t)*1000).toISOString(); }
function dateToTimestamp() { const d=document.getElementById('datetime-input').value; if(d) document.getElementById('timestamp-output').innerHTML=Math.floor(new Date(d).getTime()/1000); }
function getCurrentTimestamp() { document.getElementById('timestamp-input').value=Math.floor(Date.now()/1000); }
function clearTimestamp() { document.getElementById('timestamp-input').value=''; document.getElementById('timestamp-output').innerHTML=''; }
function encodeURL() { document.getElementById('url-output').value=encodeURIComponent(document.getElementById('url-input').value); }
function decodeURL() { try { document.getElementById('url-output').value=decodeURIComponent(document.getElementById('url-input').value); } catch(e) { document.getElementById('url-output').value='Error'; } }
function clearURL() { document.getElementById('url-input').value=''; document.getElementById('url-output').value=''; }
async function generateHash(type) { const i=document.getElementById('hash-input').value; if(!i) return; const e=new TextEncoder(); const d=e.encode(i); let h; if(type==='md5') { let x=0; for(let c of i) x=((x<<5)-x)+c.charCodeAt(0); x=Math.abs(x).toString(16).padStart(32,'0'); document.getElementById('hash-output').innerHTML+='<p><strong>MD5:</strong> '+x+'</p>'; return; } else { h=await crypto.subtle.digest(type==='sha1'?'SHA-1':type==='sha256'?'SHA-256':'SHA-512',d); } const a=Array.from(new Uint8Array(h)); const hex=a.map(b=>b.toString(16).padStart(2,'0')).join(''); document.getElementById('hash-output').innerHTML+='<p><strong>'+type.toUpperCase()+':</strong> '+hex+'</p>'; }
function clearHash() { document.getElementById('hash-input').value=''; document.getElementById('hash-output').innerHTML=''; }
function generateCron() { const m=document.getElementById('cron-minute').value; const h=document.getElementById('cron-hour').value; const d=document.getElementById('cron-day').value; const mo=document.getElementById('cron-month').value; const w=document.getElementById('cron-weekday').value; const expr=m+' '+h+' '+d+' '+mo+' '+w; document.getElementById('cron-expression').textContent=expr; let desc=''; if(m==='*') desc='Every minute'; else if(m==='0') desc='At minute 0'; if(h==='*') desc+=' of every hour'; else if(h==='0') desc+=' at midnight'; else if(h==='9') desc+=' at 9 AM'; else if(h==='17') desc+=' at 5 PM'; if(d!=='*') desc+=' on day '+d; if(w==='1-5') desc+=' on weekdays'; document.getElementById('cron-description').textContent=desc; updateNextRuns(expr); }
function parseCron() { const expr=document.getElementById('cron-parse-input').value; document.getElementById('cron-expression').textContent=expr; updateNextRuns(expr); }
function updateNextRuns(expr) { const runs=[]; const now=new Date(); for(let i=0;i<5;i++) { const next=new Date(now.getTime()+i*900000); runs.push(next.toISOString().replace('T',' ').substring(0,19)); } document.getElementById('cron-next-runs').innerHTML=runs.map(r=>'<li>'+r+'</li>').join(''); }
function generateUUID() { document.getElementById('uuid-output').innerHTML='<p>'+createUUID(document.getElementById('uuid-version').value)+'</p>'; }
function generateBulkUUID() { const count=parseInt(document.getElementById('uuid-count').value)||1; const uuids=[]; for(let i=0;i<Math.min(count,100);i++) uuids.push(createUUID(document.getElementById('uuid-version').value)); document.getElementById('uuid-output').innerHTML=uuids.map(u=>'<p>'+u+'</p>').join(''); }
function createUUID(v) { if(v==='v4') return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){const r=Math.random()*16|0;const va=c==='x'?r:(r&0x3|0x8);return va.toString(16);}); else if(v==='v1') { const t=Date.now().toString(16).padStart(12,'0'); return t.slice(0,8)+'-'+t.slice(8,12)+'-1xxx-xxxx-xxxxxxxxxxxx'.replace(/[x]/g,()=>Math.floor(Math.random()*16).toString(16)); } else { const t=Date.now().toString(16).padStart(12,'0'); return t.slice(0,8)+'-'+t.slice(8,12)+'-7xxx-xxxx-xxxxxxxxxxxx'.replace(/[x]/g,()=>Math.floor(Math.random()*16).toString(16)); } }
function copyAllUUID() { navigator.clipboard.writeText(document.getElementById('uuid-output').textContent); }
function showStatus(id,msg,type) { const el=document.getElementById(id); el.textContent=msg; el.className='status '+type; setTimeout(()=>el.textContent='',3000); }
function copyToClipboard(id) { const el=document.getElementById(id); if(el) navigator.clipboard.writeText(el.value||el.textContent); }
function hexToRgb(hex) { const r=/^#?([a-f\d]{2})$/i.exec(hex); return r?{r:parseInt(r[1],16),g:parseInt(r[1],16)>>8||parseInt(r[1].slice(0,2),16),b:parseInt(r[1])||parseInt(r[1].slice(-2),16)}:{r:0,g:0,b:0}; }
function rgbToHsl(r,g,b) { r/=255;g/=255;b/=255; const max=Math.max(r,g,b),min=Math.min(r,g,b); let h,s,l=(max+min)/2; if(max===min){h=s=0;}else{const d=max-min; s=l>0.5?d/(2-max-min):d/(max+min); switch(max){case r:h=((g-b)/d+(g<b?6:0))/6;break;case g:h=((b-r)/d+2)/6;break;case b:h=((r-g)/d+4)/6;break;}} return {h:Math.round(h*360),s:Math.round(s*100),l:Math.round(l*100)}; }
